-- Create ENUM type for account_type
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type OWNER TO cse340;

-- Create classification table
CREATE TABLE public.classification 
(
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name VARCHAR NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory 
(
	inv_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	inv_make VARCHAR NOT NULL,
	inv_model VARCHAR NOT NULL,
	inv_year VARCHAR NOT NULL,
	inv_description TEXT NOT NULL,
	inv_image VARCHAR NOT NULL,
	inv_thumbnail VARCHAR NOT NULL,
	inv_price NUMERIC(9,0) NOT NULL,
	inv_miles INT NOT NULL,
	inv_color VARCHAR NOT NULL,
	classification_id INT NOT NULL,
	CONSTRAINT fk_classification FOREIGN KEY (classification_id)
		REFERENCES public.classification (classification_id)
		ON UPDATE CASCADE
);

-- Create account table
CREATE TABLE IF NOT EXISTS public.account
(
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_firstname VARCHAR NOT NULL,
    account_lastname VARCHAR NOT NULL,
    account_email VARCHAR NOT NULL,
    account_password VARCHAR NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'
);

-- Insert classification data
INSERT INTO public.classification (classification_name)
VALUES 
	('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');

-- Insert inventory data (sample)
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description,
    inv_image, inv_thumbnail, inv_price, inv_miles,
    inv_color, classification_id
)
VALUES
('Chevy','Camaro','2018','If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
 '/images/camaro.jpg','/images/camaro-tn.jpg',25000,101222,'Silver',2),

('GM','Hummer','2016','Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
 '/images/hummer.jpg','/images/hummer-tn.jpg',58800,56564,'Yellow',4);

-- (Add all your other inventory rows here like in your seed file)

-----------------------------------------------------------
-- EXTRA QUERIES REQUIRED BY ASSIGNMENT (at the end only)
-----------------------------------------------------------

-- 4. Update GM Hummer description
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- 6. Update image paths to include /vehicles
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
